services:
    cashpos-backend:
        build:
            context: ./docker
            dockerfile: 8.3/Dockerfile
        image: general/php-8.3
        container_name: cashpos-backend
        volumes:
            - .:/var/www/html
        ports:
            - "8023:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - cashpos-network
        extra_hosts:
            - "host.docker.internal:host-gateway"

    cashpos-node:
        image: node:22-alpine
        container_name: cashpos-node
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run build"
        networks:
            - cashpos-network

networks:
    cashpos-network:
        driver: bridge
